import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import localFont from "next/font/local";

const galvji = localFont({
  src: [
    {
      path: "../assets/galvji.ttf",
      weight: "400",
    },
    {
      path: "../assets/galvji-bold.ttf",
      weight: "700",
    },
  ],
});

export const metadata: Metadata = {
  title: "Pallas Electrical",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-screen flex flex-col ${galvji.className}`}>
        <Navbar />
        <section className="flex-1 flex">{children}</section>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
