import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });
const galvji = localFont({ src: "../assets/galvji.ttf" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-screen flex flex-col ${galvji.className}`}>
        <Navbar />
        <section className="flex-1 flex">{children}</section>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
